docker_repo: docker-ce.repo

# Docker user
docker_user: jgaba

# WEB SERVER
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 82:82
web_dockerfile_path: docker/web/

# DB SERVER
db_docker_img_name: db
db_docker_img_tag: latest
db_container_name: dbserver
db_ports: 3307:3307
db_dockerfile_path: docker/db/
